# Generated by Django 4.0.3 on 2022-04-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=20, verbose_name='Second Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True, verbose_name='Age')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('per_address', models.TextField(verbose_name='Present Address')),
                ('section', models.CharField(choices=[('nur', 'Nursery'), ('pri', 'Primary'), ('jss', 'Junior'), ('sss', 'Senior')], default=1, max_length=10, verbose_name='Section')),
                ('class_room', models.CharField(max_length=20, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='classSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, verbose_name='Section')),
                ('classes', models.CharField(max_length=30, unique=True, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, verbose_name='New Session')),
                ('date_added', models.DateField(auto_now=True, verbose_name='Date Added')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sponsor/Guardian Name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('per_address', models.TextField(verbose_name='Address')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='admission.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Next of Kin Name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('per_address', models.TextField(verbose_name='Address')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextofkins', to='admission.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted', models.BooleanField(default=False, verbose_name='Admitted')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admission.applicant')),
                ('session', models.ForeignKey(default='2022/2023', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admission.session')),
            ],
            options={
                'ordering': ['session'],
            },
        ),
    ]
