# Generated by Django 4.0.3 on 2022-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admission.applicant'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admission.session'),
        ),
    ]
