# Generated by Django 4.0.3 on 2022-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_session_status_alter_admission_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=9, unique=True, verbose_name='New Session'),
        ),
    ]
