# Generated by Django 4.0.3 on 2022-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.CharField(default=0, max_length=10, verbose_name='Current Session'),
        ),
    ]
