# Generated by Django 4.0.3 on 2022-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_session_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sessions',
            field=models.CharField(default='2022/2023', max_length=20, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.applicant'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.applicant'),
        ),
    ]
