# Generated by Django 4.0.3 on 2022-04-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_addressof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addressof',
        ),
    ]
